#pragma once

struct RIP;
class SO;
class CM;
struct LSG;

struct VTRIP;
struct VTDROPLET;
struct VTBUBLET;
struct VTRIPPLE;
struct VTPUFF;
struct VTDABLET;
struct VTFLAKE;
struct VTSPARK;
struct VTBURST;
struct VTTRAIL;
struct VTFIREBALL;
struct VTSMOKECLOUD;
struct VTSMOKETRAIL;
struct VTDEBRIS;
struct VTORBIT;
struct VTSMACK;
struct VTRAY;
struct VTROSE;
struct VTFLYING;
struct VTSTUCK;
struct VTLEAF;
struct VTFLAME;
struct VTBULLET;
struct VTSHRAPNEL;
struct VTGLINT;
struct VTMATCH;
struct VTREMIT;

extern VTRIP g_vtrip;
extern VTDROPLET g_vtdroplet;
extern VTBUBLET g_vtbublet;
extern VTRIPPLE g_vtripple;
extern VTPUFF g_vtpuff;
extern VTDABLET g_vtdablet;
extern VTFLAKE g_vtflake;
extern VTSPARK g_vtspark;
extern VTBURST g_vtburst;
extern VTTRAIL g_vttrail;
extern VTFIREBALL g_vtfireball;
extern VTSMOKECLOUD g_vtsmokecloud;
extern VTSMOKETRAIL g_vtsmoketrail;
extern VTDEBRIS g_vtdebris;
extern VTORBIT g_vtorbit;
extern VTSMACK g_vtsmack;
extern VTRAY g_vtray;
extern VTROSE g_vtrose;
extern VTFLYING g_vtflying;
extern VTSTUCK g_vtstuck;
extern VTLEAF g_vtleaf;
extern VTFLAME g_vtflame;
extern VTBULLET g_vtbullet;
extern VTSHRAPNEL g_vtshrapnel;
extern VTGLINT g_vtglint;
extern VTMATCH g_vtmatch;
extern VTREMIT g_vtremit;
