#pragma once
#include "lo.h"

using PFNGETOBJECTLIST = int (*)(BASIC* pbasic, void* pvstate);

struct SPLOPT 
{
    int optid;
    struct EOPID *peopid;
};

struct ARYSPLOPT 
{
    int csplopt;
    SPLOPT* asplopt;
};

struct GLS 
{
    OTYP otyp;
    std::shared_ptr <CPair> ppairHead;
    std::shared_ptr <CPair> ppairPrev;
};

CRef RefAddOption(BASIC* pbasic, int optid, CRef* prefValue);
CRef RefEnsureOption(BASIC* pbasic, int optid, CRef* prefValue);
CRef RefGetOption(BASIC* pbasic, int optid);
CRef RefSetOption(BASIC* pbasic, int optid, CRef* prefValue);
CRef RefGetPeopid(BASIC* pbasic, EOPID* peopid);
CRef RefGetObjectList(BASIC* pbasic, OTYP otyp, PFNGETOBJECTLIST pfnget);
CRef RefSetPeopid(BASIC* pbasic, EOPID* peopid, CRef* prefValue);
EOPID* PeopidFind(BASIC* pbasic, int optid);
CRef RefSetPvsFromSplice(int cref, CRef* aref, OTYP* aotyp, void** apv);
CRef RefSetArgListFromPvs(int cargs, OTYP* aotyp, void** apv);
int FAppendSpliceListElement(void* pvstate, void* pvdata);
int FSpliceListElementExists(void* pvstate, void* pvdata);

extern SPLOPT g_asploptBasic[2];
extern SPLOPT g_asploptLo[21];
extern SPLOPT g_asploptAlo[127];
extern SPLOPT g_asploptSo[149];
extern SPLOPT g_asploptMs[149];
extern SPLOPT g_asploptPo[153];
extern SPLOPT g_asploptStep[156];
extern SPLOPT g_asploptJt[170];
extern SPLOPT g_asploptStepguard[198];
extern SPLOPT g_asploptSmartguard[211];
extern SPLOPT g_asploptGomer[208];
extern SPLOPT g_asploptUbg[208];
extern SPLOPT g_asploptMbg[203];
extern SPLOPT g_asploptBhg[201];
extern SPLOPT g_asploptMurray[201];
extern SPLOPT g_asploptPuffc[198];
extern SPLOPT g_asploptCrfod[198];
extern SPLOPT g_asploptCrfodb[199];
extern SPLOPT g_asploptCrfodk[198];
extern SPLOPT g_asploptRuby[207];
extern SPLOPT g_asploptTank[158];
extern SPLOPT g_asploptRov[154];
extern SPLOPT g_asploptTurret[160];
extern SPLOPT g_asploptVault[158];
extern SPLOPT g_asploptPuffer[156];
extern SPLOPT g_asploptSuv[176];
extern SPLOPT g_asploptLgn[177];
extern SPLOPT g_asploptUnk0[156];
extern SPLOPT g_asploptRythm[155];
extern SPLOPT g_asploptMgv[159];
extern SPLOPT g_asploptRipg[149];
extern SPLOPT g_asploptWater[160];
extern SPLOPT g_asploptBrk[179];
extern SPLOPT g_asploptBreak[179];
extern SPLOPT g_asploptAlbrk[180];
extern SPLOPT g_asploptDartgun[186];
extern SPLOPT g_asploptSwp[184];
extern SPLOPT g_asploptFragile[183];
extern SPLOPT g_asploptZapbreak[184];
extern SPLOPT g_asploptBrkp[153];
extern SPLOPT g_asploptButton[165];
extern SPLOPT g_asploptVolbtn[163];
extern SPLOPT g_asploptJlovol[167];
extern SPLOPT g_asploptBone[149];
extern SPLOPT g_asploptSprize[152];
extern SPLOPT g_asploptScprize[152];
extern SPLOPT g_asploptClue[155];
extern SPLOPT g_asploptAlarm[158];
extern SPLOPT g_asploptSensor[163];
extern SPLOPT g_asploptLasen[167];
extern SPLOPT g_asploptCamsen[167];
extern SPLOPT g_asploptPrsen[179];
extern SPLOPT g_asploptBarrier[153];
extern SPLOPT g_asploptIkh[149];
extern SPLOPT g_asploptTzp[156];
extern SPLOPT g_asploptVolzp[156];
extern SPLOPT g_asploptChkpnt[152];
extern SPLOPT g_asploptCnvo[150];
extern SPLOPT g_asploptHbsk[152];
extern SPLOPT g_asploptBomb[169];
extern SPLOPT g_asploptMissile[175];
extern SPLOPT g_asploptAccmiss[178];
extern SPLOPT g_asploptTarmiss[179];
extern SPLOPT g_asploptMine[169];
extern SPLOPT g_asploptFly[167];
extern SPLOPT g_asploptRat[160];
extern SPLOPT g_asploptRoh[150];
extern SPLOPT g_asploptRoc[153];
extern SPLOPT g_asploptRost[149];
extern SPLOPT g_asploptRop[149];
extern SPLOPT g_asploptDart[155];
extern SPLOPT g_asploptJlo[156];
extern SPLOPT g_asploptPufft[149];
extern SPLOPT g_asploptMrkv[152];
extern SPLOPT g_asploptClkwork[154];
extern SPLOPT g_asploptClkwrkdmg[151];
extern SPLOPT g_asploptDecoy[152];
extern SPLOPT g_asploptBlipg[127];
extern SPLOPT g_asploptCamera[133];
extern SPLOPT g_asploptLbone[127];
extern SPLOPT g_asploptEmitter[200];
extern SPLOPT g_asploptLight[149];
extern SPLOPT g_asploptSch[127];
extern SPLOPT g_asploptProxy[127];
extern SPLOPT g_asploptSky[128];
extern SPLOPT g_asploptDprize[133];
extern SPLOPT g_asploptCharm[133];
extern SPLOPT g_asploptLifetkn[134];
extern SPLOPT g_asploptCoin[134];
extern SPLOPT g_asploptKey[133];
extern SPLOPT g_asploptGold[134];
extern SPLOPT g_asploptBoost[133];
extern SPLOPT g_asploptLock[127];
extern SPLOPT g_asploptLockg[130];
extern SPLOPT g_asploptTail[135];
extern SPLOPT g_asploptRob[160];
extern SPLOPT g_asploptFlash[128];
extern SPLOPT g_asploptDysh[127];
extern SPLOPT g_asploptWaypoint[130];
extern SPLOPT g_asploptTn[163];
extern SPLOPT g_asploptJloc[136];
extern SPLOPT g_asploptDialog[140];
extern SPLOPT g_asploptSpeaker[139];
extern SPLOPT g_asploptWm[127];
extern SPLOPT g_asploptCrfodkSpawn[149];
extern SPLOPT g_asploptHubsel[127];
extern SPLOPT g_asploptHubprog[127];
extern SPLOPT g_asploptUnk11[127];
extern SPLOPT g_asploptSw[81];
extern SPLOPT g_asploptCm[39];
extern SPLOPT g_asploptShape[21];
extern SPLOPT g_asploptHshape[28];
extern SPLOPT g_asploptPipe[30];
extern SPLOPT g_asploptRail[28];
extern SPLOPT g_asploptLanding[21];
extern SPLOPT g_asploptXfm[25];
extern SPLOPT g_asploptWarp[35];
extern SPLOPT g_asploptTarget[28];
extern SPLOPT g_asploptHnd[35];
extern SPLOPT g_asploptExpl[25];
extern SPLOPT g_asploptExplg[27];
extern SPLOPT g_asploptExplo[44];
extern SPLOPT g_asploptExpls[93];
extern SPLOPT g_asploptVol[26];
extern SPLOPT g_asploptRathole[26];
extern SPLOPT g_asploptExit[34];
extern SPLOPT g_asploptPnt[23];
extern SPLOPT g_asploptHpnt[30];
extern SPLOPT g_asploptJmt[25];
extern SPLOPT g_asploptSpire[25];
extern SPLOPT g_asploptScan[23];
extern SPLOPT g_asploptAseg[33];
extern SPLOPT g_asploptAsegbl[33];
extern SPLOPT g_asploptViszone[21];
extern SPLOPT g_asploptVismap[21];
extern SPLOPT g_asploptFrzg[22];
extern SPLOPT g_asploptSm[23];
extern SPLOPT g_asploptSgg[23];
extern SPLOPT g_asploptPathzone[22];
extern SPLOPT g_asploptRchm[27];
extern SPLOPT g_asploptRwm[62];
extern SPLOPT g_asploptWr[41];
extern SPLOPT g_asploptKeyhole[21];
extern SPLOPT g_asploptJsg[38];
extern SPLOPT g_asploptRythmSequence[27];
extern SPLOPT g_asploptUnk14[29];
extern SPLOPT g_asplotAsega[13];
extern SPLOPT g_asploptSma[11];
extern ARYSPLOPT g_mpcidarysplopt[148];