/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-126523-g884590dd4a-20260912"
#endif /* AVUTIL_FFVERSION_H */
