#pragma once

// Forward declarations

class CBinaryInputStream;
class LO;
class ALO;
class SO;
class JT;
class STEPGUARD;
class MBG;
class ROV;
class ROH;
class ROC;
class ROST;
class ROP;
class PUFFER;
class MGV;
class BRK;
class BUTTON;
class VOLBTN;
class SQUISH;
class SPRIZE;
class CLUE;
class LOCK;
class LOCKG;
class LASEN;
class CNVO;
class HBSK;
class BOMB;
class MISSILE;
class FLY;
class RAT;
class DART;
class JLO;
class JLOC;
class CHKPNT;
class VOL;
class FLASH;
class TN;
class DIALOG;
class MGC;
class JACKN;
class SHAPE;
class WARP;
class EXIT;
class HND;
class ASEG;
class SM;
class PATHZONE;
class RCHM;
class DPRIZE;
class PNT;
class KEYHOLE;
class PROXY;
extern bool loadEmitMesh;

void LoadProxyFromBrx(PROXY* pproxy, CBinaryInputStream* pbis);
void LoadKeyholeFromBrx(KEYHOLE* pkeyhole, CBinaryInputStream* pbis);
void LoadVismapFromBrx(CBinaryInputStream* pbis);
void LoadSoFromBrx(SO* pso, CBinaryInputStream* pbis);
void LoadJtFromBrx(JT* pjt, CBinaryInputStream* pbis);
void LoadStepGuardFromBrx(STEPGUARD* pstepguard, CBinaryInputStream* pbis);
void LoadMbgFromBrx(MBG* pmbg, CBinaryInputStream* pbis);
void LoadRovFromBrx(ROV* prov, CBinaryInputStream* pbis);
void LoadRohFromBrx(ROH* proh, CBinaryInputStream* pbis);
void LoadRocFromBrx(ROC* proc, CBinaryInputStream* pbis);
void LoadRostFromBrx(ROST* prost, CBinaryInputStream* pbis);
void LoadRopFromBrx(ROP* prop, CBinaryInputStream* pbis);
void LoadPufferFromBrx(PUFFER* ppuffer, CBinaryInputStream* pbis);
void LoadMgvFromBrx(MGV* pmgv, CBinaryInputStream* pbis);
void LoadBrkFromBrx(BRK* pbrk, CBinaryInputStream* pbis);
void LoadButtonFromBrx(BUTTON* pbutton, CBinaryInputStream* pbis);
void LoadVolbtnFromBrx(VOLBTN* pvolbtn, CBinaryInputStream* pbis);
void LoadSquishFromBrx(SQUISH* psquish, CBinaryInputStream* pbis);
void LoadSprizeFromBrx(SPRIZE* psprize, CBinaryInputStream* pbis);
void LoadClueFromBrx(CLUE* pclue, CBinaryInputStream* pbis);
void LoadLockFromBrx(LOCK* plock, CBinaryInputStream* pbis);
void LoadLockgFromBrx(LOCKG* plockg, CBinaryInputStream* pbis);
void LoadLasenFromBrx(LASEN* plasen, CBinaryInputStream* pbis);
void LoadCnvoFromBrx(CNVO* pcnvo, CBinaryInputStream* pbis);
void LoadHbskFromBrx(HBSK* phbsk, CBinaryInputStream* pbis);
void LoadBombFromBrx(BOMB* pbomb, CBinaryInputStream* pbis);
void LoadMissileFromBrx(MISSILE* pmissile, CBinaryInputStream* pbis);
void LoadFlyFromBrx(FLY* pfly, CBinaryInputStream* pbis);
void LoadRatFromBrx(RAT* prat, CBinaryInputStream* pbis);
void LoadRovFromBrx(ROV* prov, CBinaryInputStream* pbis);
void LoadRohFromBrx(ROH* proh, CBinaryInputStream* pbis);
void LoadEmitterFromBrx(CBinaryInputStream* pbis);
void LoadRocFromBrx(ROC* proc, CBinaryInputStream* pbis);
void LoadRostFromBrx(ROST* prost, CBinaryInputStream* pbis);
void LoadRopFromBrx(ROP* prop, CBinaryInputStream* pbis);
void LoadDartFromBrx(DART* pdart, CBinaryInputStream* pbis);
void LoadJloFromBrx(JLO* pjlo, CBinaryInputStream* pbis);
void LoadJlocFromBrx(JLOC* pjloc, CBinaryInputStream* pbis);
void LoadChkpntFromBrx(CHKPNT* pchkpnt, CBinaryInputStream* pbis);
void LoadExploFromBrx(CBinaryInputStream* pbis);
void LoadPntFromBrx(PNT* pnt, CBinaryInputStream* pbis);
void LoadExplgFromBrx(CBinaryInputStream* pbis);
void LoadVolFromBrx(VOL* pvol, CBinaryInputStream* pbis);
void LoadSprizeFromBrx(SPRIZE* psprize, CBinaryInputStream* pbis);
void LoadDprizeFromBrx(DPRIZE* pdprize, CBinaryInputStream* pbis);
void LoadClueFromBrx(CLUE* pclue, CBinaryInputStream* pbis);
void LoadLockFromBrx(LOCK* plock, CBinaryInputStream* pbis);
void LoadLockgFromBrx(LOCKG* plockg, CBinaryInputStream* pbis);
void LoadFlashFromBrx(FLASH* pflash, CBinaryInputStream* pbis);
void LoadTnFromBrx(TN* ptn, CBinaryInputStream* pbis);
void LoadTbspFromBrx(CBinaryInputStream* pbis);
void LoadJloFromBrx(JLO* pjlo, CBinaryInputStream* pbis);
void LoadJlocFromBrx(JLOC* pjloc, CBinaryInputStream* pbis);
void LoadDialogFromBrx(DIALOG* pdialog, CBinaryInputStream* pbis);
void LoadMgcFromBrx(MGC* pmgc, CBinaryInputStream* pbis);
void LoadJacknFromBrx(JACKN* pjackn, CBinaryInputStream* pbis);
void LoadShapeFromBrx(SHAPE* pshape, CBinaryInputStream* pbis);
void LoadXfmFromBrx(CBinaryInputStream* pbis);
void LoadWarpFromBrx(WARP* pwarp, CBinaryInputStream* pbis);
void LoadExitFromBrx(EXIT* pexit, CBinaryInputStream* pbis);
void LoadHndFromBrx(HND* phnd, CBinaryInputStream* pbis);
void LoadChkpntFromBrx(CHKPNT* pchkpnt, CBinaryInputStream* pbis);
void LoadVolFromBrx(VOL* pvol, CBinaryInputStream* pbis);
void LoadAsegFromBrx(ASEG* paseg, CBinaryInputStream* pbis);
void LoadSmFromBrx(SM* psm, CBinaryInputStream* pbis);
void LoadPathZoneFromBrx(PATHZONE* ppathzone, CBinaryInputStream* pbis);
void LoadRchmFromBrx(RCHM* prchm, CBinaryInputStream* pbis);